<%@ Page Title="" Language="C#" MasterPageFile="~/hlm/Site1.Master" AutoEventWireup="true" CodeBehind="jurnal.aspx.cs" Inherits="bumdesAPP.hlm.jurnal" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="body">
        <h3 style="font-weight:400; text-align:left">
            BUMDES TUNAS MANDIRI DESA NEGARA RATU<br />
            JURNAL<br /></h3>
        <br />
        <asp:Table ID="Table2" Width="487px" style="padding:17px; border: solid 1px #ccc; border-radius:10px" runat="server">
            <asp:TableRow>
                <asp:TableCell style="text-align:right; padding-right:20px" Width="160px">No. Transaksi</asp:TableCell>
                <asp:TableCell Height="40px" style="padding-left: 17px">
                    <asp:Label ID="lblnoTransaksi" runat="server" Text=""></asp:Label>
                    <asp:Label ID="lblBoolEdit" runat="server" ForeColor="black" Text=""></asp:Label>
                    <asp:Label ID="lbltrjp" runat="server" Text="Label"></asp:Label>
                </asp:TableCell>
            </asp:TableRow>
            <asp:TableRow>
                <asp:TableCell style="text-align:right; padding-right:20px" Width="160px">No. Jurnal</asp:TableCell>
                <asp:TableCell Height="40px" style="padding-left: 17px">
                    <asp:Label ID="lblnoJurnal" runat="server" Text=""></asp:Label>
                </asp:TableCell>
            </asp:TableRow>
            <asp:TableRow>
                <asp:TableCell style="text-align:right; padding-right:20px" Width="160px">Deskripsi</asp:TableCell>
                <asp:TableCell Height="40px" style="padding-left: 17px">
                    <asp:Label ID="lbldeskripsi" runat="server" Text=""></asp:Label>
                </asp:TableCell>
            </asp:TableRow>
            <asp:TableRow>
                <asp:TableCell style="text-align:right; padding-right:20px" Width="160px">Nominal</asp:TableCell>
                <asp:TableCell Height="40px" style="padding-left: 17px">
                    <asp:Label DataFormatString="{0:n0}" ID="lblNominal" runat="server" Text=""></asp:Label>
                </asp:TableCell>
            </asp:TableRow>
        </asp:Table>
        <asp:Table ID="Table1" style="padding:17px; border: solid 1px #ccc; border-radius:10px" Width="487px" runat="server">
            <asp:TableRow>
                <asp:TableCell style="text-align:right; padding-right:20px">Debet<a style="color:red">*</a></asp:TableCell>
                <asp:TableCell Height="40px"><asp:DropDownList ID="DropDownListRekening" runat="server" CssClass="textboxstyle" BorderColor="#1DA1F2" BorderStyle="Solid" 
                    BorderWidth="1px" style="color:#666" ForeColor="#000CCC" Width="314px" Height="38px"></asp:DropDownList></asp:TableCell>
            </asp:TableRow>
             <asp:TableRow>
                <asp:TableCell style="text-align:right; padding-right:20px">Kredit<a style="color:red">*</a></asp:TableCell>
                <asp:TableCell Height="40px"><asp:DropDownList ID="DropDownListRekening2" runat="server" CssClass="textboxstyle" BorderColor="#1DA1F2" BorderStyle="Solid" 
                    BorderWidth="1px" style="color:#666" ForeColor="#000CCC" Width="314px" Height="38px"></asp:DropDownList></asp:TableCell>
            </asp:TableRow>
            <asp:TableRow>
                <asp:TableCell>
                    <asp:Label ID="lblCekSaldo" runat="server"></asp:Label></asp:TableCell>
                <asp:TableCell HorizontalAlign="Right" Height="40px"><asp:Button ID="simpanData" runat="server" Text="Simpan" style="border-radius: 16px" BackColor="#1DA1F2" BorderStyle="none" 
                    ForeColor="white" Height="34px" Width="90px" OnClick="simpanData_Click"/></asp:TableCell>
            </asp:TableRow>
        </asp:Table>
        <%--<asp:Label ID="lbldatajurnalblmada" Visible="false" runat="server" Text=""></asp:Label>--%>
        <%--<asp:GridView ID="GridView2" AutoGenerateDeleteButton="true" OnRowDeleting="GridView2_RowDeleting" CssClass="cssgridview" AlternatingRowStyle-CssClass="alt" 
             runat="server" OnRowDataBound="GridView2_RowDataBound" ShowFooter="true" AutoGenerateColumns="false">
            <Columns>
                <asp:BoundField HeaderText="REKENING" DataField="rekeningID" HeaderStyle-Width="30%" ItemStyle-HorizontalAlign="Left" HeaderStyle-HorizontalAlign="Left" />
                <asp:BoundField HeaderText="DEBET" DataField="debet" HeaderStyle-Width="30%" ItemStyle-HorizontalAlign="Right" FooterStyle-HorizontalAlign="Right" />
                <asp:BoundField HeaderText="KREDIT" DataField="kredit" HeaderStyle-Width="30%" ItemStyle-HorizontalAlign="Right" FooterStyle-HorizontalAlign="Right"  />
            </Columns>
        </asp:GridView>--%>
        <%--<asp:Table Width="100%" runat="server">
            <asp:TableRow>
                <asp:TableCell><asp:Label ID="lbltotaldkhrssama" Text="" runat="server"></asp:Label><asp:Label ID="testdebetkredit" runat="server"></asp:Label></asp:TableCell>
                <asp:TableCell HorizontalAlign="Right"><asp:Button ID="simpanDataBtn" runat="server" Text="Simpan" style="border-radius: 16px" BorderStyle="none" Height="34px" Width="90px" OnClientClick="return alert('Data Detail Jurnal Tersimpan.')" OnClick="simpanDataBtn_Click"/></asp:TableCell></asp:TableRow>
        </asp:Table>--%>
        <div style="text-align: center"><asp:Label ID="lblgridview1" Visible="false" Text="TRANSAKSI YANG BELUM DIJURNAL<br/>" runat="server"></asp:Label></div>
        <asp:Label ID="lbltidakadadatatransaksi" Visible="false" runat="server" Text="<br/>Tidak Ada Data Transaksi. (Redirecting...)"></asp:Label>
        <asp:GridView ID="GridView1" runat="server" CssClass="cssgridview" AlternatingRowStyle-CssClass="alt" AutoGenerateColumns="false" >
            <Columns>
                <asp:BoundField HeaderText="TANGGAL" DataField="tanggal" HeaderStyle-Width="15%" HeaderStyle-HorizontalAlign="Left" DataFormatString="{0:dd-MM-yy}" />
                <asp:BoundField HeaderText="DESKRIPSI" DataField="deskripsi" HeaderStyle-Width="50%" HeaderStyle-HorizontalAlign="Left" />
                <asp:BoundField HeaderText="NO. TRANSAKSI" DataField="noTransaksi" HeaderStyle-Width="15%" HeaderStyle-HorizontalAlign="Left" />
                <asp:BoundField HeaderText="NOMINAL" DataField="nominal" HeaderStyle-Width="10%" DataFormatString="{0:n0}" ItemStyle-HorizontalAlign="Right" />
                <asp:TemplateField HeaderStyle-Width="10%" ItemStyle-HorizontalAlign="Center">
                    <ItemTemplate>
                        <asp:LinkButton ID="linkPilih" Text="Pilih" runat="server" CommandArgument='<%# Eval("transaksiID") %>' OnClick="linkPilih_Click" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <asp:Button ID="tambahJurnalButton" runat="server" Text="Tambah Jurnal" style="border-radius: 16px" BorderStyle="none" 
                    Height="34px" Width="120px" OnClick="tambahJurnalBtn_Click"/>
        <br />
        <br />
        <asp:Table ID="TablePertanggalSort" runat="server">
            <asp:TableRow>
                <asp:TableCell style="width:120px">Periode<div style="font-size:11px">(mm/dd/yyyy)</div></asp:TableCell>
                <asp:TableCell>:</asp:TableCell>
                <asp:TableCell><asp:TextBox ID="TextBoxPeriode1" TextMode="Date" runat="server" CssClass="textboxstyle" BorderColor="#1da1f2" BorderStyle="Solid" BorderWidth="1px" style="color:#666" ForeColor="#ccc" Width="150px" Height="34px"></asp:TextBox></asp:TableCell>
                <asp:TableCell>s.d</asp:TableCell>
                <asp:TableCell><asp:TextBox ID="TextBoxPeriode2" TextMode="Date" runat="server" CssClass="textboxstyle" BorderColor="#1da1f2" BorderStyle="Solid" BorderWidth="1px" style="color:#666" ForeColor="#ccc" Width="150px" Height="34px"></asp:TextBox></asp:TableCell>
                <asp:TableCell><asp:Button ID="lihatJurnalPertanggal" runat="server" Text="Lihat" style="background-color:#1DA1F2; border-radius: 16px" ForeColor="white" BorderStyle="none" Height="34px" Width="100px" OnClick="lihatJurnalPertanggal_Click" /></asp:TableCell>
            </asp:TableRow>
        </asp:Table>
        <br />
        <div style="text-align:center"><asp:Label ID="lblKetJurnal" runat="server" Text=""></asp:Label></div>
        <asp:GridView ID="GridView3" runat="server" CssClass="cssgridview" AlternatingRowStyle-CssClass="alt" AutoGenerateColumns="false" OnPageIndexChanging="GridView3_PageIndexChanging" AllowPaging="true" PagerSettings-Visible="true" PageSize="15" >
            <Columns>
                <asp:BoundField HeaderText="NO. JURNAL" DataField="noJurnal" HeaderStyle-Width="15%" HeaderStyle-HorizontalAlign="Left"/>
                <asp:BoundField HeaderText="TANGGAL" DataField="tanggal" HeaderStyle-Width="10%" HeaderStyle-HorizontalAlign="Left" DataFormatString="{0:dd-MM-yy}" />
                <asp:BoundField HeaderText="DESKRIPSI" DataField="deskripsi" HeaderStyle-Width="48%" HeaderStyle-HorizontalAlign="Left" />
                <asp:BoundField HeaderText="NO. TRANSAKSI" DataField="noTransaksi" HeaderStyle-Width="15%" HeaderStyle-HorizontalAlign="Left" />
                <asp:TemplateField HeaderStyle-Width="12%" HeaderText="Opsi" ItemStyle-HorizontalAlign="Center">
                    <ItemTemplate>
                        <asp:LinkButton ID="linkEdit" Text="Edit" runat="server" CommandArgument='<%# Eval("transaksiID") %>' OnClick="linkEdit_Click"></asp:LinkButton>
                        <asp:LinkButton ID="linkHapus" Text="Hapus" runat="server" CommandArgument='<%# Eval("noJurnal") %>' OnClientClick="return confirm('Data Detail Jurnal juga akan Terhapus. Apakah Ingin Menghapus Data?')" OnClick="linkHapus_Click"></asp:LinkButton>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <br />
        <asp:Label ID="LabelHalaman" runat="server"></asp:Label>
    </div>
    <script>
        function hanyaAngka(evt) {
            var charcode = (evt.which) ? evt.which : event.keyCode
            if (charcode > 31 && (charcode < 48 || charcode > 57))
                return false;
            return true;
        }
        </script>
</asp:Content>
